### ISSUE TITLE
`assign` optimizer not ideal

### ISSUE THREAD

**Issue by richardkiss** [Chia-Network/clvm_tools_rs_fork#162]
Here are two equivalent bits of code: one uses stages, another uses assign. The assign version is significantly more expensive.

```
% brun -c -x $(opc "$(run double-stages.clsp)") 80
cost = 62153
((0x7268f8652403026d2d22f0f6acf813bd8c1b2a4fb09671313c5d1b89e3905271 . 0x3c173081c3cabf976a1fc330a584044dc7d6eda2f4c46eeede7c4a36f3bbf3d5) . 0x0081554cf0ba111b2c871f6070ce67898df910fc9984e7e4edd6cac2271100e68d)
% brun -c -x $(opc "$(run double-assign.clsp)") 80
cost = 1270054
((0x7268f8652403026d2d22f0f6acf813bd8c1b2a4fb09671313c5d1b89e3905271 . 0x3c173081c3cabf976a1fc330a584044dc7d6eda2f4c46eeede7c4a36f3bbf3d5) . 0x0081554cf0ba111b2c871f6070ce67898df910fc9984e7e4edd6cac2271100e68d)
```

Files attached in gist below.

**Comment by richardkiss** [comment]
The `.clsp` files are available here https://gist.github.com/richardkiss/cdce7e95afa66d1dfa3f6ba182a60313

**Comment by prozacchiwawa** [comment]
with assign-lambda, cost is
cost = 62372
((0x7268f8652403026d2d22f0f6acf813bd8c1b2a4fb09671313c5d1b89e3905271 . 0x3c173081c3cabf976a1fc330a584044dc7d6eda2f4c46eeede7c4a36f3bbf3d5) . 0x0081554cf0ba111b2c871f6070ce67898df910fc9984e7e4edd6cac2271100e68d)

**Comment by prozacchiwawa** [comment]
will be interesting to see if i can ensure that it gets the low cost version without having to specify.

**Comment by richardkiss** [comment]
I tried using `assign-lambda` on nightly, but as of a7303739bdca98f5f63e3ebec784de640bea242f it doesn't seem to be supported yet.
